services:
  api:
    build:
      context: ./src
    environment:
      - ASPNETCORE_URLS=http://*:5071
    ports:
      - 5071:5071
    depends_on:
      - database
  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql